# Site
repository: marc-cenon/marc-cenon.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: MARC CENON
title: Ingénieur SysAdmin - DevOps
email: marc.cenon33@gmail.com
website: https://marc-cenon.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  marc-cenon
linkedin_username: marccenon33

# About Section
about_title: Présentation
about_profile_image: images/myAvatar.png
about_content: | # this will include new lines to allow paragraphs
  Marc ... 35 ans ... trail runner ... beer drinker ..... passionné d'informatique et de nouvelles technologies

  Mes points forts: <mark>Linux</mark> --- <mark>Docker</mark> --- <mark>Kubernetes</mark> --- <mark>Ansible</mark>  --- <mark>CI/CD</mark>

  - Mes compétences:
      - IaC: Ansible, Terraform, K8s, Docker, Packer
      - OS: Red Hat, CentOs, Debian, Ubuntu, Arch, Windows
      - Scripting: Bash, Python
      - CI/CD: Github, Gitlab, Helm, ArgoCD, Flux
      - Monitoring: Influxdb, Prometheus, Grafana, Telegraf, Loki, Promtail, Centreon
      - Virtualisation: Proxmox, Vmware (ESXi, Vsphere), Virtualbox, Qemu
      - Web: Apache, Nginx, Haproxy, Traefik
      - BDD: Mysql, Mariadb, Postgresql, Mongo, Influxdb
      - Providers: OVH, AWS
      - Autres: Veeam, Jira, Confluence

content:
  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      ![Certs](./images/certs.png "CERTS")

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CGI
        link: cgi.com/france/fr-fr
        caption: 2021 - Aujourd'hui
        description: | # this will include new lines to allow paragraphs
          Ingénieur SysAdmin / Devops
          - Principales technologies utilisées: Linux - VMWARE - Ansible - Docker - Kubernetes - CI/CD

      - layout: top-middle
        title: Bureau Feret
        caption: 2018 - 2020
        description: | # this will include new lines to allow paragraphs
          Courtage Vins - Support Informatique
          - Principales technologies utilisées: Docker - Mysql - Linux - Windows

      - layout: top-middle
        title: Chateau Marquis de Terme
        caption: 2015 - 2018
        description: | # this will include new lines to allow paragraphs
          Assistant oenotourisme et communication digitale
          - Principales technologies utilisées: Windows - Linux - Nginx - Wordpress - Facebook

      - layout: top-middle
        title: Equaline
        caption: 2012 - 2014
        description: | # this will include new lines to allow paragraphs
          Technicien Hotline
          - Principales technoligies utilisées: Divers CRM - Windows - outils Cisco

      - layout: top-middle
        title: Teleperformance
        caption: 2009 - 2012
        description: | # this will include new lines to allow paragraphs
          Conseiller technique confirmé
          - Principales technologies utilisées: Windows, divers CRM

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Université de Bordeaux
        caption: 2020 - 2021
        sub_title: Licence Profesionnelle ADSILLH
        description: | # this will include new lines to allow paragraphs
          Adminitration / Développement de Systèmes Informatiques à base de Logiciels Libres et Hybrides

      - layout: top-middle
        title: WSET School of London
        caption: 2017 - 2017
        sub_titlle: WSET Level 3
        description: | # this will include new lines to allow paragraphs
          Diplôme International en sommelerie et oenologie (Bac +3)

      - layout: top-middle
        title: Université de Bordeaux
        caption: 2020 - 2021
        sub_title: Licence LEA Anglais - Japonais - Parcours Marketing International
        description: | # this will include new lines to allow paragraphs
        <font size="+4"><center>Licence en Marketing International avec échange culturel au Japon</center></font>

  - title: Hobbies
    layout: text
    content: | # this will include new lines to allow paragraphs
      Quelques centres d'iintêrets:
      - Trail running
      - Canicross
      - Cuisine
      - Informatique
      - Voyages
      - Livres de syfy

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
