# Site
repository: marc-cenon/marc-cenon.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: MARC CENON
title: Ingénieur SysAdmin - DevOps
email: marc.cenon33@gmail.com
website: https://marc-cenon.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  marc-cenon
linkedin_username: marccenon33

# About Section
about_title: Présentation
about_profile_image: images/myAvatar.png
about_content: | # this will include new lines to allow paragraphs
  Marc ... 35 ans ... trail runner ... beer drinker ..... passionné d'informatique et de nouvelles technologies

  - Mon champs d'action:
      - <mark>IaC</mark>: Ansible, Terraform, K8s, Docker, Packer
      - <mark>OS</mark>: Red Hat, CentOs, Debian, Ubuntu, Arch, Windows
      - <mark>Scripting</mark>: Bash, Python, Rust, Golang, Lua
      - <mark>CI/CD</mark>: Github, Gitlab, Helm, ArgoCD, Flux
      - <mark>Monitoring</mark>: Influxdb, Prometheus, Grafana, Telegraf, Loki, Promtail, Centreon
      - <mark>Virtualisation</mark>: Proxmox, Vmware (ESXi, Vsphere), Virtualbox, Qemu
      - <mark>Web</mark>: Apache, Nginx, Haproxy, Traefik, Open
      - <mark>BDD</mark>: Mysql, Mariadb, Postgresql, Mongo, Influxdb
      - <mark>Providers</mark>: OVH, AWS, Azure
      - <mark>Autres</mark>: Veeam, Jira, Confluence

content:
  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      ![Certs](./images/certs.png "CERTS")

  - title: Expérience # Title for the section
    layout: list # Type of content section (list/text)
    content:
     - layout: top-middle
        title: CSHIELD - BALEEN
        link: https://baleen.cloud
        caption: 2022 - Aujourd'hui
        description: | # this will include new lines to allow paragraphs
          <font size="5"><center> Ingénieur Devops </center></font>
          <font size="4"><center> (Linux - Ansible - Docker - Kubernetes - CI/CD - Terraform - Rust - Python) </center></font>
          
      - layout: top-middle
        title: CGI
        link: cgi.com/france/fr-fr
        caption: 2021 - Aujourd'hui
        description: | # this will include new lines to allow paragraphs
          <font size="5"><center> Ingénieur SysAdmin / Devops </center></font>
          <font size="4"><center> (Linux - VMWARE - Ansible - Docker - Kubernetes - CI/CD) </center></font>

      - layout: top-middle
        title: Bureau Feret
        caption: 2018 - 2020
        description: | # this will include new lines to allow paragraphs
          <font size="5"><center> Courtage Vins - Support Informatique </center></font>
          <font size="4"><center> (Docker - Mysql - Linux - Windows) </center></font>

      - layout: top-middle
        title: Chateau Marquis de Terme
        caption: 2015 - 2018
        description: | # this will include new lines to allow paragraphs
          <font size="5"><center> Assistant oenotourisme et communication digitale </center></font>
          <font size="4"><center> (Windows - Linux - Nginx - Wordpress) </center></font>

      - layout: top-middle
        title: Equaline
        caption: 2012 - 2014
        description: | # this will include new lines to allow paragraphs
          <font size="5"><center> Technicien Hotline </center></font>
          <font size="4"><center> (Divers CRM - Windows) </center></font>

      - layout: top-middle
        title: Teleperformance
        caption: 2009 - 2012
        description: | # this will include new lines to allow paragraphs
          <font size="5"><center> Conseiller technique confirmé </center></font>
          <font size="4"><center> (Windows, divers CRM) </center></font>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Université de Bordeaux
        caption: 2020
        sub_title: Licence Profesionnelle ADSILLH
        description: | # this will include new lines to allow paragraphs
          <font size="4"><center> Adminitration / Développement de Systèmes Informatiques à base de Logiciels Libres et Hybrides </center></font>

      - layout: top-middle
        title: WSET School of London
        caption: 2017
        sub_titlle: WSET Level 3
        description: | # this will include new lines to allow paragraphs
          <font size="4"><center> Diplôme International en sommelerie et oenologie (Bac +3) </center></font>

      - layout: top-middle
        title: Université de Bordeaux
        caption: 2013
        sub_title: Licence LEA Anglais - Japonais - Parcours Marketing International
        description: | # this will include new lines to allow paragraphs
          <font size="4"><center> Licence en Marketing International avec échange culturel au Japon </center></font>

  - title: Hobbies
    layout: text
    content: | # this will include new lines to allow paragraphs
        <font size="4"><center> Trail running </center></font>
        <font size="4"><center> Canicross </center></font>
        <font size="4"><center> Informatique </center></font>
        <font size="4"><center> Voyages </center></font>
        <font size="4"><center> Livres Syfy </center></font>
        <font size="4"><center> Bricolage </center></font>

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
