# Site
repository: marc-cenon/marc-cenon.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: MARC CENON
title: Ingénieur SysAdmin - DevOps
email: marc.cenon33@gmail.com
website: https://marc-cenon.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  marc-cenon
linkedin_username: marccenon33

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Marc ... 35 ans ... trail runner ... beer drinker ..... passionné d'informatique et de nouvelles technologies

  Mes points forts: <mark>Linux</mark> --- <mark>Docker</mark> --- <mark>Kubernetes</mark> --- <mark>Ansible</mark>  --- <mark>CI/CD</mark>
  
  - Mes compétences:
      - IaC: Ansible, Terraform, K8s, Docker, Packer
      - OS: Red Hat, CentOs, Debian, Ubuntu, Arch, Windows
      - Scripting: Bash, Python
      - CI/CD: Github, Gitlab, Helm, ArgoCD, Flux
      - Monitoring: Influxdb, Prometheus, Grafana, Telegraf, Loki, Promtail, Centreon
      - Virtualisation: Proxmox, Vmware (ESXi, Vsphere), Virtualbox, Qemu
      - Web: Apache, Nginx, Haproxy, Traefik
      - BDD: Mysql, Mariadb, Postgresql, Mongo, Influxdb
      - Providers: OVH, AWS
      - Autres: Veeam, Jira, Confluence

content:
  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      ![Certs](./images/certs.png "CERTS")

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Université de Bordeaux
        caption: 2020 - 2021
        sub_title: Licence Profesionnelle ADSILLH:
        description: | # this will include new lines to allow paragraphs
          Adminitration / Développement de Systèmes Informatiques à base de Logiciels Libres et Hybrides

      - layout: left
        title: WSET School of London
        caption: 2017 - 2017
        sub_titlle: WSET Level 3
        description: | # this will include new lines to allow paragraphs
          Diplôme International en sommelerie et oenologie (Bac +3)

      - layout: left
        title: Université de Bordeaux
        caption: 2020 - 2021
        sub_title: Licence LEA Anglais - Japonais - Parcours Marketing International
        description: | # this will include new lines to allow paragraphs
          Licence en Marketing International avec échange culturel au Japon

  - title: Hobbies
    layout: text
    content: | # this will include new lines to allow paragraphs
      Quelques centres d'iintêrets:
      - Trail running
      - Canicross
      - Cuisine
      - Informatique
      - Voyages
      - Livres syfy

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
